// Code generated by muamba. DO NOT EDIT.

package acquisition

import (
	"embed"
	"fmt"
	"io/fs"
)

//go:embed vendor/developer-icons/v7.0.1/LICENSE.txt vendor/heroicons/v2.2.0/LICENSE.txt
var muambaFiles embed.FS

const (
	muambaDownloadDeveloperIconsLicense = "license"
	muambaDownloadHeroiconsLicense      = "license"
	muambaResourceDeveloperIcons        = "developer-icons"
	muambaResourceHeroicons             = "heroicons"
)

type MuambaResource struct {
	Name      string
	Version   string
	Downloads []MuambaDownload
}

type MuambaDownload struct {
	Name      string
	URL       string
	Path      string
	Integrity string
	Hash      string
}

var muambaResources = []MuambaResource{
	{Name: "developer-icons", Version: "v7.0.1", Downloads: []MuambaDownload{
		{Name: "license", URL: "https://raw.githubusercontent.com/xandemon/developer-icons/v7.0.1/LICENSE", Path: "internal/acquisition/vendor/developer-icons/v7.0.1/LICENSE.txt", Integrity: "sha384-F8/2mCc0b+N+LRggi8nGpF/fzhEOSLu/4qEs3AmI6nKDBI+undh1oeMYnL296EV0", Hash: "sha384:17cff69827346fe37e2d18208bc9c6a45fdfce110e48bbbfe2a12cdc0988ea7283048fae9dd875a1e3189cbdbde84574"},
	}},
	{Name: "heroicons", Version: "v2.2.0", Downloads: []MuambaDownload{
		{Name: "license", URL: "https://raw.githubusercontent.com/tailwindlabs/heroicons/v2.2.0/LICENSE", Path: "internal/acquisition/vendor/heroicons/v2.2.0/LICENSE.txt", Integrity: "sha384-zZwI/O2prTGDEmLZ7zRQDU5uBHh0I9RcfsxxiBs8rVAEUeWHCkfZZuadqFVCMuoU", Hash: "sha384:cd9c08fceda9ad31831262d9ef34500d4e6e04787423d45c7ecc71881b3cad500451e5870a47d966e69da8554232ea14"},
	}},
}

var muambaEmbeddedPaths = map[string]string{
	"developer-icons\x00license": "vendor/developer-icons/v7.0.1/LICENSE.txt",
	"heroicons\x00license":       "vendor/heroicons/v2.2.0/LICENSE.txt",
}

var muambaHashes = map[string]string{
	"developer-icons\x00license": "sha384:17cff69827346fe37e2d18208bc9c6a45fdfce110e48bbbfe2a12cdc0988ea7283048fae9dd875a1e3189cbdbde84574",
	"heroicons\x00license":       "sha384:cd9c08fceda9ad31831262d9ef34500d4e6e04787423d45c7ecc71881b3cad500451e5870a47d966e69da8554232ea14",
}

func MuambaResources() []MuambaResource {
	result := make([]MuambaResource, len(muambaResources))
	copy(result, muambaResources)
	for index := range result {
		result[index].Downloads = append([]MuambaDownload(nil), result[index].Downloads...)
	}
	return result
}

func MuambaResourceByName(name string) (MuambaResource, bool) {
	for _, resource := range MuambaResources() {
		if resource.Name == name {
			return resource, true
		}
	}
	return MuambaResource{}, false
}

func MuambaHash(resource, download string) (string, bool) {
	hash, ok := muambaHashes[resource+"\x00"+download]
	return hash, ok
}

func MuambaOpen(resource, download string) (fs.File, error) {
	path, ok := muambaEmbeddedPaths[resource+"\x00"+download]
	if !ok {
		return nil, fmt.Errorf("unknown Muamba download %s/%s", resource, download)
	}
	return muambaFiles.Open(path)
}
