schema: 1
metadata:
  packs:
    - source: heroicons
      alias: hi
      release: v2.2.0
      revision: 0435d4ca364a608cc75e2f8683d374e55abbae26
      repository: https://github.com/tailwindlabs/heroicons
      source_ref: heroicons/optimized
      license: MIT
      license_ref: heroicons/license
      namespace: ui
      variants:
        - 16-solid
        - 20-solid
        - 24-outline
        - 24-solid
    - source: developer-icons
      alias: devicon
      release: v7.0.1
      revision: 28b895aba6a4984b8c43714336fafa5fa832f08f
      repository: https://github.com/xandemon/developer-icons
      source_ref: developer-icons/icons
      license: MIT
      license_ref: developer-icons/license
      namespace: brand
      variants:
        - default
        - dark
        - light
